ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Models/ErrorViewModel.cs
namespace ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Models/Producto.cs
namespace ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY.Models
{
    public class Producto
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public decimal Precio { get; set; }
    }
}

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Controllers/HomeController.cs
using System.Diagnostics;
using ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Controllers/ProductoController.cs
using ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY.Data;
using ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProducto _iproducto;

        public ProductoController(IProducto iproducto)
        {
            _iproducto = iproducto;
        }

        //Read
        public IActionResult Index()
        {
            var producto = _iproducto.ObtenerProductos();
            return View(producto);
        }

        public IActionResult Detalle(int id)
        {
            var producto = _iproducto.ObtenerProductoPorId(id);
            return View(producto);
        }

        //Create
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Crear(Producto producto)
        {
            _iproducto.InsertarProducto(producto);
            return RedirectToAction("index");
        }

        //Edit
        public IActionResult Editar(int id)
        {
            var producto = _iproducto.ObtenerProductoPorId(id);
            return View(producto);
        }

        [HttpPost]
        public IActionResult Editar(Producto producto)
        {
            _iproducto.ActualizarProducto(producto);
            return RedirectToAction("index");
        }

        //Delete
        public IActionResult Eliminar(int id)
        {
            var producto = _iproducto.ObtenerProductoPorId(id);
            if(producto == null)
                return NotFound();
            return View(producto);
        }

        [HttpPost]
        public IActionResult EliminarConfirmado(int id)
        {
            _iproducto.EliminarProducto(id);
            return RedirectToAction("index");
        }
    }
}

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Views/Producto/Crear.cshtml
@model Producto

<h1>Crear nuevo Producto</h1>
<form asp-action="Crear" method="post">
	<div class="form-group">
		<label asp-for="Nombre" class="control-label"></label>
		<input asp-for="Nombre" class="form-control"/>
		<span asp-validation-for="Nombre" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Precio" class="control-label"></label>
		<input asp-for="Precio" class="form-control" />
		<span asp-validation-for="Precio" class="text-danger"></span>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Guardar</button>
		<a asp-action="Index" class="btn btn-secondary">Cancelar</a>
	</div>
</form>

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Views/Producto/Detalle.cshtml
@model Producto

<h1>Detalle del producto</h1>

<dl class="row">
	<dt class="col-sm-2">Nombre</dt>
	<dt class="col-sm-10">@Model.Nombre</dt>

	<dt class="col-sm-2">Precio</dt>
	<dt class="col-sm-10">@Model.Precio.ToString("C")</dt>
</dl>
<a asp-action="Index" class="btn btn-secondary">Regresar a la lista de productos</a>

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Views/Producto/Editar.cshtml
@model Producto

<h1>Editar Producto</h1>
<form asp-action="Editar" method="post">
	<input type="hidden" asp-for="Id" />
	<div class="form-group">
		<label asp-for="Nombre" class="control-label"></label>
		<input asp-for="Nombre" class="form-control"/>
		<span asp-validation-for="Nombre" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Precio" class="control-label"></label>
		<input asp-for="Precio" class="form-control" />
		<span asp-validation-for="Precio" class="text-danger"></span>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">Guardar</button>
		<a asp-action="Index" class="btn btn-secondary">Cancelar</a>
	</div>
</form>

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Views/Producto/Eliminar.cshtml
@model Producto

<h1>Eliminar producto</h1>
<h3>Estás seguro que deseas eliminar el siguiente producto?</h3>

<dl class="row">
	<dt class="col-sm-2">Nombre</dt>
	<dt class="col-sm-10">@Model.Nombre</dt>

	<dt class="col-sm-2">Precio</dt>
	<dt class="col-sm-10">@Model.Precio.ToString("C")</dt>
</dl>
<form asp-action="EliminarConfirmado" method="post">
	<input asp-for="Id" type="hidden"/>
	<div class="form-group">
		<button type="submit" class="btn btn-danger">Eliminar</button>
		<a asp-action="Index" class="btn btn-secondary">Cancelar</a>
	</div>
</form>

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Views/Producto/Index.cshtml
@model IEnumerable<Producto>

	<h1>Productos</h1>
	<p>
		<a asp-action="Crear" class="btn btn-success">Crear nuevo producto</a>
	</p>

	<table class="table">
		<thead>
			<tr>
				<th>Nombre</th>
				<th>Precio</th>
			</tr>
		</thead>
		<tbody>
		@foreach (var producto in Model)
		{
			<tr>
				<td>@producto.Nombre</td>
				<td>@producto.Precio.ToString("C")</td>
				<td>
					<a asp-action="Detalle" class="btn btn-info" asp-route-id="@producto.Id">Detalle</a>
					<a asp-action="Editar" class="btn btn-warning" asp-route-id="@producto.Id">Editar</a>
					<a asp-action="Eliminar" class="btn btn-danger" asp-route-id="@producto.Id">Eliminar</a>
				</td>
			</tr>
		}
		</tbody>
	</table>

ASP CORE MVC DAPPER STORED PROCEDURES REPOSITORY/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASP_CORE_MVC_DAPPER_STORED_PROCEDURES_REPOSITORY - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>